In [129]:
from fetchYahooStockData import metadata_price_action, extended_stock_stats, basic_stats, current_sp500_symbols, parse_value, current_dow30_symbols
import numpy as np
import pandas as pd

In [130]:
symbol="AMD"
timeInterval = "1d"
longTimeInterval = "1wk"
timeRange = "5y"

In [131]:
metadataAndPrice = metadata_price_action(symbol, timeInterval, timeRange)
metadata = metadataAndPrice["metadata"]
metadata

https://query1.finance.yahoo.com/v8/finance/chart/AMD?symbol=AMD&region=US&lang=en-US&includePrePost=false&interval=1d&useYfid=true&range=5y&corsDomain=finance.yahoo.com&.tsrc=finance

{'currency': 'USD',
 'symbol': 'AMD',
 'exchangeName': 'NMS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 322151400,
 'regularMarketTime': 1614978002,
 'gmtoffset': -18000,
 'timezone': 'EST',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 78.52,
 'chartPreviousClose': 2.37,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EST',
   'start': 1614934800,
   'end': 1614954600,
   'gmtoffset': -18000},
  'regular': {'timezone': 'EST',
   'start': 1614954600,
   'end': 1614978000,
   'gmtoffset': -18000},
  'post': {'timezone': 'EST',
   'start': 1614978000,
   'end': 1614992400,
   'gmtoffset': -18000}},
 'dataGranularity': '1d',
 'range': '5y',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [132]:
longMetadataAndPrice = metadata_price_action(symbol, longTimeInterval, timeRange)
longMetadata = metadataAndPrice["metadata"]
longMetadata

https://query1.finance.yahoo.com/v8/finance/chart/AMD?symbol=AMD&region=US&lang=en-US&includePrePost=false&interval=1wk&useYfid=true&range=5y&corsDomain=finance.yahoo.com&.tsrc=finance

{'currency': 'USD',
 'symbol': 'AMD',
 'exchangeName': 'NMS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 322151400,
 'regularMarketTime': 1614978002,
 'gmtoffset': -18000,
 'timezone': 'EST',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 78.52,
 'chartPreviousClose': 2.37,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EST',
   'start': 1614934800,
   'end': 1614954600,
   'gmtoffset': -18000},
  'regular': {'timezone': 'EST',
   'start': 1614954600,
   'end': 1614978000,
   'gmtoffset': -18000},
  'post': {'timezone': 'EST',
   'start': 1614978000,
   'end': 1614992400,
   'gmtoffset': -18000}},
 'dataGranularity': '1d',
 'range': '5y',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [133]:
from typing import Dict, List, Optional, Sequence, Union
from numbers import Number

def _data_period(index) -> Union[pd.Timedelta, Number]:
    """Return data index period as pd.Timedelta"""
    values = pd.Series(index[-100:])
    return values.diff().dropna().median()

In [188]:
price = metadataAndPrice["price"]
# price.columns = ["timestamp", "Close", "Open", "High", "Volume", "Low"]
price = price.dropna()
price["Close"]=price["close"]
price["High"]=price["high"]
price["Low"]=price["low"]
price["Open"]=price["open"]
price["Volume"]=price["volume"]
del price['close']
del price['high']
del price['low']
del price['open']
del price['volume']

price['timestamp']=price["timestamp"].apply(lambda x: pd.Timestamp(x, unit='s').to_datetime64())
price['timestamp']=pd.DatetimeIndex(price["timestamp"])

price = price.set_index('timestamp')
price

                         Close       High        Low       Open    Volume
timestamp
2016-03-07 14:30:00   2.470000   2.470000   2.360000   2.360000   8754300
2016-03-08 14:30:00   2.300000   2.460000   2.300000   2.440000  10026900
2016-03-09 14:30:00   2.260000   2.350000   2.200000   2.320000  13082400
2016-03-10 14:30:00   2.260000   2.310000   2.150000   2.290000   9603500
2016-03-11 14:30:00   2.520000   2.540000   2.290000   2.290000  21382400
...                        ...        ...        ...        ...       ...
2021-03-01 14:30:00  86.389999  86.500000  83.970001  85.370003  32716700
2021-03-02 14:30:00  84.129997  86.949997  84.040001  86.919998  34773100
2021-03-03 14:30:00  80.860001  84.379997  80.849998  84.279999  43471600
2021-03-04 14:30:00  77.750000  81.809998  76.779999  80.230003  60252900
2021-03-05 14:30:00  78.519997  79.480003  74.199997  79.000000  58484000

[1259 rows x 5 columns]

In [179]:
longPrice = longMetadataAndPrice["price"]
# longPrice.columns = ["timestamp", "Close", "Open", "High", "Volume", "Low"]
longPrice

      timestamp     volume       open        low       high      close
0    1457326800   62849500   2.360000   2.150000   2.540000   2.520000
1    1457928000  123768600   2.530000   2.450000   2.930000   2.930000
2    1458532800   43988000   2.900000   2.620000   2.900000   2.790000
3    1459137600   53575000   2.810000   2.700000   2.980000   2.830000
4    1459742400   49734100   2.830000   2.610000   2.870000   2.740000
..          ...        ...        ...        ...        ...        ...
257  1612760400  201713800  88.309998  87.980003  94.220001  93.769997
258  1613365200  132524600  93.900002  87.309998  94.000000  89.580002
259  1613970000  231033500  88.150002  79.360001  88.300003  84.510002
260  1614574800  229698300  85.370003  74.199997  86.949997  78.519997
261  1614978002   58103511  79.000000  74.199997  79.480003  78.519997

[262 rows x 6 columns]

In [189]:
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from backtesting.test import SMA, GOOG
from statistics import mean
# print(GOOG, GOOG.index.dtype, GOOG.dtypes)
def mySMA(myArr, period):
    return pd.Series(myArr).rolling(period).mean()
            
def myEMA(myArr, period):
    return pd.Series(myArr).ewm(adjust=False, span=period).mean()
    
def myMacd(myArr):
    twelve = myEMA(myArr, 8) 
    twentySix = myEMA(myArr, 26)
    macd = twelve-twentySix
    return macd

def myMacdSignal(myArr):
    return myEMA(myMacd(myArr), 9)

def myMacdHist(myArr):
    return myMacd(myArr) - myMacdSignal(myArr)
    
class SmaCross(Strategy):
    def init(self):
        tempprice = self.data.Close
        self.ma1 = self.I(myEMA, tempprice, 8)
        self.ma2 = self.I(myEMA, tempprice, 26)
#         self.macd = self.I(myMacd, tempprice)
#         self.macdSignal = self.I(myMacdSignal, tempprice)
#         self.macdHist = self.I(myMacdHist, tempprice)

    def next(self):
        if crossover(self.ma1, self.ma2):
            self.buy()
        elif crossover(self.ma2, self.ma1):
            self.sell()

print(price, price.index.dtype, price.dtypes)
bt = Backtest(price, SmaCross,
              exclusive_orders=True)
stats = bt.run()
bt.plot()
stats

                         Close       High        Low       Open    Volume
timestamp
2016-03-07 14:30:00   2.470000   2.470000   2.360000   2.360000   8754300
2016-03-08 14:30:00   2.300000   2.460000   2.300000   2.440000  10026900
2016-03-09 14:30:00   2.260000   2.350000   2.200000   2.320000  13082400
2016-03-10 14:30:00   2.260000   2.310000   2.150000   2.290000   9603500
2016-03-11 14:30:00   2.520000   2.540000   2.290000   2.290000  21382400
...                        ...        ...        ...        ...       ...
2021-03-01 14:30:00  86.389999  86.500000  83.970001  85.370003  32716700
2021-03-02 14:30:00  84.129997  86.949997  84.040001  86.919998  34773100
2021-03-03 14:30:00  80.860001  84.379997  80.849998  84.279999  43471600
2021-03-04 14:30:00  77.750000  81.809998  76.779999  80.230003  60252900
2021-03-05 14:30:00  78.519997  79.480003  74.199997  79.000000  58484000

[1259 rows x 5 columns] datetime64[ns] Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

ValueError: Invalid value for `superimpose`: Upsampling not supported.

In [181]:
basicStats = basic_stats(symbol)
basicStats

{'Previous Close': '77.75',
 'Open': '79.00',
 'Bid': '78.88 x 1000',
 'Ask': '78.90 x 900',
 "Day's Range": '74.20 - 79.48',
 '52 Week Range': '36.75 - 99.23',
 'Volume': '58,103,511',
 'Avg. Volume': '42,843,283',
 'Market Cap': '95.113B',
 'Beta (5Y Monthly)': '2.18',
 'PE Ratio (TTM)': '38.04',
 'EPS (TTM)': '2.06',
 'Earnings Date': 'Apr 26, 2021 - Apr 30, 2021',
 'Forward Dividend & Yield': 'N/A (N/A)',
 'Ex-Dividend Date': 'Apr 27, 1995'}

In [158]:
extStats = extended_stock_stats(symbol)
extStats

{'Market Cap (intraday) 5': ['101.91B',
  '111.16B',
  '98.55B',
  '61.76B',
  '53.26B',
  '53.66B'],
 'Enterprise Value 3': ['100.15B',
  '109.97B',
  '97.67B',
  '61.08B',
  '52.48B',
  '53.56B'],
 'Trailing P/E ': ['40.84', '123.93', '157.67', '122.35', '151.60', '241.37'],
 'Forward P/E 1': ['44.25', '51.02', '49.26', '52.63', '39.84', '43.48'],
 'PEG Ratio (5 yr expected) 1': ['1.57',
  '1.13',
  '1.42',
  '1.55',
  '1.66',
  '1.55'],
 'Price/Sales (ttm)': ['10.40', '12.68', '12.67', '8.37', '7.57', '8.38'],
 'Price/Book (mrq)': ['17.46', '28.72', '29.82', '20.34', '18.84', '24.66'],
 'Enterprise Value/Revenue 3': ['10.26',
  '33.90',
  '34.87',
  '31.61',
  '29.39',
  '25.18'],
 'Enterprise Value/EBITDA 6': ['59.76',
  '167.63',
  '193.41',
  '238.59',
  '202.63',
  '180.94'],
 'Beta (5Y Monthly) ': '2.18',
 '52-Week Change 3': '81.47%',
 'S&P500 52-Week Change 3': '39.88%',
 '52 Week High 3': '99.23',
 '52 Week Low 3': '36.75',
 '50-Day Moving Average 3': '88.06',
 '200-Day Moving Average 3': '86.07',
 'Avg Vol (3 month) 3': '42.84M',
 'Avg Vol (10 day) 3': '46.76M',
 'Shares Outstanding 5': '1.21B',
 'Float ': '1.2B',
 '% Held by Insiders 1': '0.62%',
 '% Held by Institutions 1': '73.87%',
 'Shares Short (Feb 11, 2021) 4': '80.45M',
 'Short Ratio (Feb 11, 2021) 4': '1.68',
 'Short % of Float (Feb 11, 2021) 4': '6.68%',
 'Short % of Shares Outstanding (Feb 11, 2021) 4': '6.64%',
 'Shares Short (prior month Jan 14, 2021) 4': '71.35M',
 'Forward Annual Dividend Rate 4': 'N/A',
 'Forward Annual Dividend Yield 4': 'N/A',
 'Trailing Annual Dividend Rate 3': 'N/A',
 'Trailing Annual Dividend Yield 3': 'N/A',
 '5 Year Average Dividend Yield 4': 'N/A',
 'Payout Ratio 4': '0.00%',
 'Dividend Date 3': 'N/A',
 'Ex-Dividend Date 4': 'Apr 26, 1995',
 'Last Split Factor 2': '2:1',
 'Last Split Date 3': 'Aug 21, 2000',
 'Fiscal Year Ends ': 'Dec 25, 2020',
 'Most Recent Quarter (mrq)': 'Dec 25, 2020',
 'Profit Margin ': '25.50%',
 'Operating Margin (ttm)': '14.02%',
 'Return on Assets (ttm)': '11.42%',
 'Return on Equity (ttm)': '57.48%',
 'Revenue (ttm)': '9.76B',
 'Revenue Per Share (ttm)': '8.25',
 'Quarterly Revenue Growth (yoy)': '52.50%',
 'Gross Profit (ttm)': '4.35B',
 'EBITDA ': '1.68B',
 'Net Income Avi to Common (ttm)': '2.49B',
 'Diluted EPS (ttm)': '2.06',
 'Quarterly Earnings Growth (yoy)': '947.60%',
 'Total Cash (mrq)': '2.29B',
 'Total Cash Per Share (mrq)': '1.89',
 'Total Debt (mrq)': '572M',
 'Total Debt/Equity (mrq)': '9.80',
 'Current Ratio (mrq)': '2.54',
 'Book Value Per Share (mrq)': '4.82',
 'Operating Cash Flow (ttm)': '1.07B'}